// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface EnvironmentItem {
    "Name": string;
    "Value": string;
}

export interface ProcessEventMessage {
    "Status": string;
    "Log": string;
}

export interface RunOption {
    "LogMaxLine": number;
    "AutoRun": boolean;
    "WorkDir": string;
}

export interface RunParams {
    "Name": string;
    "CommandName": string;
    "Args": string[] | null;
    "Environment": EnvironmentItem[] | null;
}
