// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ProcessEventMessage {
    "Status": string;
    "Log": string;
}

export interface RunParams {
    "Name": string;
    "CommandName": string;
    "Args": string[] | null;
    "Environment": string[] | null;
    "WorkDir": string;
}
