// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ProcessEventMessage {
    "Status": string;
    "Log": string;
}

export interface RunOption {
    "AutoLaunch": boolean;
    "WorkDir": string;
    "StartCommand": string;
    "StopCommand": string;
    "Environment": string[] | null;
    "LogMaxLine": number;
}
