// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function EventEmit(eventName: string, message: $models.ProcessEventMessage | null): $CancellablePromise<void> {
    return $Call.ByID(4023712442, eventName, message);
}

export function GetEventName(processName: string): $CancellablePromise<string> {
    return $Call.ByID(1612482016, processName);
}

export function GetProcessStatus(name: string): $CancellablePromise<$models.ProcessEventMessage> {
    return $Call.ByID(1508088688, name);
}

export function Run(name: string, option: $models.RunOption): $CancellablePromise<boolean> {
    return $Call.ByID(815717712, name, option);
}

export function Stop(name: string): $CancellablePromise<void> {
    return $Call.ByID(53003887, name);
}
