// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as process$0 from "../process/models.js";

export interface AllSetting {
    "System": System;
    "Apps": App[] | null;
}

export interface App {
    "Name": string;
    "HomeUrl"?: string;
    "RunOption": process$0.RunOption;
    "Setting"?: Setting;
}

export interface EnvironmentItem {
    "Description": string;
    "DefaultValue"?: string;
}

export type FormAppEnvironment = {"name": string, "environment": string[] | null}[] | null;

export interface Setting {
    "Environment": { [_ in string]?: EnvironmentItem } | null;
}

export interface System {
    "CloseWindowHide": boolean;
    "Theme": string;
}
