// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AllConfig {
    "System": System;
    "Apps": App[] | null;
}

export interface App {
    "Name": string;
    "Environment": EnvironmentItem[] | null;
    "CommandName": string;
    "Args": string[] | null;
    "AutoRun": boolean;
}

export interface EnvironmentItem {
    "Name": string;
    "Value": string;
    "Label": EnvironmentLabelItem;
}

export interface EnvironmentLabelItem {
    "ZhCN": string;
    "EnUS": string;
}

export interface System {
    "AutoLaunch": boolean;
    "CloseWindowHide": boolean;
    "Theme": string;
}
