// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as process$0 from "../process/models.js";

export interface AllConfig {
    "System": System;
    "Apps": App[] | null;
}

export interface App {
    "Name": string;
    "HomeUrl": string;
    "RunOption": process$0.RunOption;
    "Setting": Setting;
}

export interface EnvironmentLabelItem {
    "ZhCN": string;
    "EnUS": string;
}

export interface Setting {
    "Environment": { [_: string]: EnvironmentLabelItem } | null;
}

export interface System {
    "AutoLaunch": boolean;
    "CloseWindowHide": boolean;
    "Theme": string;
}
