// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as function$0 from "../../function/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAll(): $CancellablePromise<$models.AllSetting> {
    return $Call.ByID(3750558084);
}

export function GetApp(name: string): $CancellablePromise<$models.App | null> {
    return $Call.ByID(3956420844, name);
}

export function GetAutoLaunchStatus(): $CancellablePromise<function$0.Response | null> {
    return $Call.ByID(1374284227);
}

export function OpenFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(4230578371, path);
}

export function OpenHomeDir(): $CancellablePromise<boolean> {
    return $Call.ByID(1247439987);
}

export function OpenWorkDir(): $CancellablePromise<boolean> {
    return $Call.ByID(2945154633);
}

export function SaveAppEnvironment(env: $models.FormAppEnvironment): $CancellablePromise<function$0.Response | null> {
    return $Call.ByID(835905426, env);
}

export function SaveAutoLaunchStatus(status: boolean): $CancellablePromise<function$0.Response | null> {
    return $Call.ByID(426509468, status);
}

export function SaveSystem(value: $models.System): $CancellablePromise<function$0.Response | null> {
    return $Call.ByID(2383245223, value);
}
