// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetOSInfo():Promise<main.OSInfoResult>;

export function Greet(arg1:string):Promise<string>;

export function ProcessRun(arg1:string,arg2:Array<string>):Promise<boolean>;
