// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOSInfo() {
  return window['go']['main']['App']['GetOSInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ProcessRun(arg1, arg2) {
  return window['go']['main']['App']['ProcessRun'](arg1, arg2);
}
