name: release
permissions: write-all
on:
  push:
    tags:
      - 'v*'

jobs:
  windows-build:
    strategy:
      matrix:
        platform: [ 'windows-latest' ]
        go-version: [ '1.25' ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Test Env
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{ github.ref_name }}"
          echo "Tag name from github.ref: ${{ github.ref }}"
          echo "Runner OS: ${{ runner.os }}"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Download Resource
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          $headers = @{} # 如果需要认证头，比如 GitHub Token
          # PowerShell 脚本内联或从文件读取
          $files = @(
            @{ url = "https://github.com/donknap/dpanel/releases/download/docker-cli-v1/docker-windows-x86_64.exe"; out = "build\windows\resource\docker.exe" },
            @{ url = "https://github.com/donknap/dpanel/releases/download/docker-cli-v1/docker-compose-windows-x86_64.exe"; out = "build\windows\resource\docker-compose.exe" },
            @{ url = "https://github.com/donknap/dpanel/releases/download/${env:GITHUB_REF_NAME}/dpanel.exe"; out = "build\windows\resource\dpanel.exe" }
          )

          New-Item -ItemType Directory -Path "build\windows\resource" -Force

          foreach ($file in $files) {
            Write-Host "Downloading $($file.url)"
            try {
              Invoke-WebRequest -Uri $file.url -Headers $headers -OutFile $file.out -ErrorAction Stop
              if (Test-Path $file.out) {
                Write-Host "✅ Downloaded: $($file.out)"
              } else {
                throw "❌ Failed to download: $($file.url)"
              }
            } catch {
              Write-Host "❌ Error: $($_.Exception.Message)"
              exit 1
            }
          }
        shell: pwsh
      - name: Install wails3
        run: |
          go install github.com/wailsapp/wails/v3/cmd/wails3@latest
          echo "wails3 installed at $env:GOPATH\bin\wails3.exe"
          echo "$env:GOPATH\bin" >> $env:GITHUB_PATH
        env:
          GOPATH: ${{ runner.workspace }}/go
        shell: pwsh

      - name: Build
        run: |
          wails3 task windows:create:nsis:installer
        shell: pwsh

      - name: Upload artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: build/*
          prerelease: false