// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * A Level is the importance or severity of a log event.
 * The higher the level, the more important or severe the event.
 * 
 * Values are arbitrary, but there are four predefined ones.
 */
export type Level = number;

/**
 * Predefined constants for type Level.
 * @namespace
 */
export const Level = {
    Debug: -4,
    Info: 0,
    Warning: 4,
    Error: 8,
};
